# Generated by Django 6.0.5 on 2026-06-12 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.CharField(choices=[('HUMAN', 'Human'), ('VAMPIRE', 'Vampire'), ('WITCH', 'Witch'), ('WEREWOLF', 'Werewolf'), ('DOPPELGANGER', 'Doppelgänger'), ('HYBRID', 'hybrid')], default='HUMAN', max_length=20)),
                ('location', models.TextField(default='Mystic Falls', max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
